### PR TITLE
2001.1.0 Release

### LINKED ISSUE #27: ROS2 Version
I'm wondering if AutonomouStuff is interested in maintaining a ROS2 version of this driver. One has been created at https://github.com/neil-rti/avt_vimba_camera by @neil-rti but I'm not sure that RTI wants to maintain it long-term. If RTI _does_ want to maintain the ROS2 version, we should clarify on this repo that RTI's should be used for ROS2 and vice versa. If not, a PR should be made from Neil's repo to this repo (@icolwell-as - could you make a `ros2` branch in case this is the desired outcome?).

### PR DESCRIPTION
**Pull request by icolwell-as**
Resolves #27 by Releasing the first ROS2 version of this driver.

This 2001.1.0 version will coincide with an updated 1.1.0 release of the ROS1 driver.

### CODE REVIEW

**Comment by icolwell-as** [comment]
Tested with GigE Mako G-319. Works as expected.
Hoping @Souphis has time on Monday to test on the USB camera to confirm it works.

**Review by dvangeyn-as — APPROVED** [review]

**Comment by gbartyzel** [comment]
@icolwell-as So, I managed to run USB cameras with this version. However, there are some problems with the parameter server. Some float parameters cannot be set after reading them from cameras. For example, the gain range is (0.0, 8.0), the current cameras gain is 2.6, and then the driver gives an error that, the value is out of the range. The same happens with exposure_time, etc, the problem doesn't exist with auto mode enabled. 
Also, I think there should be a service for stopping and starting cameras. To set the purpose of the GPIO you have to choose the line and then set the feature value. When doing this during runtime, the driver freezes.

**Comment by icolwell-as** [comment]
Thanks for testing @Souphis! I can't seem to reproduce your gain/exposure parameters issues with my camera. I suggest creating a new issue and describing the steps you followed to reproduce the issues/errors.
Regarding the service for starting/stopping the camera, each time a parameter is updated, the camera stream is stopped and started again, see [here](https://github.com/astuff/avt_vimba_camera/blob/ros2_master/src/avt_vimba_camera.cpp#L876). Is this not working quite right for you?

Anyway, since we are in a bit of a time crunch, and this version mostly works, I'm going to go ahead and release this version, then we can work on updates to resolve your issues for a future release. 

Thanks again for testing and confirming it works!

**Comment by gbartyzel** [comment]
@icolwell-as ok, so release it. If you don't mind I can try to rewrite it to life cycle node (this will resolve the need for start/stop). And about this parameter error, I will try to reproduce this today or in the proceeding days.

**Review by jilinzhouas — APPROVED** [review]

**Comment by icolwell-as** [comment]
@Souphis certainly! happy to take any PR you think is an improvement into consideration! lifecycle is probably the best way to handle the parameter changes.

**Pull request merged**
