### PR TITLE
[ROS1] Add License

### LINKED ISSUE #64: Add LICENCE files

### PR DESCRIPTION
**Pull request by icolwell-as**
ROS1 version of PR #65, resolves #64.

### CODE REVIEW

**Review by dvangeyn-as — APPROVED** [review]

**Comment by shan-as** [comment]
Is the year correct on the license?

**Comment by icolwell-as** [comment]
I think so, I think the year is supposed to represent when you first established the copyright, like basically the first time you published your work to the world with the given terms.

**Comment by dvangeyn-as** [comment]
> I think so, I think the year is supposed to represent when you first established the copyright, like basically the first time you published your work to the world with the given terms.

Makes sense then. I was misunderstanding where and when it came from.

**Comment by icolwell-as** [comment]
Here's a reference: 

> The general rule is that the year to include in a copyright notice is the year of first publication of the work. First publication is when the work is made available to the public without restriction.

https://www.copyrightlaws.com/copyright-symbol-notice-year/

**Review by shan-as — APPROVED** [review]

**Pull request merged**
