### PR TITLE
more pixels formats for bayer

### PR DESCRIPTION
**Pull request by ghost**
Hi,

Please consider only the changes of my commit 'add support to more bayer pixel formats'.
It is very minimal modification, in src/avt_vimba_camera.cpp, definition of static const char* PixelFormatMode[] (line 60).
Simply, and it works. Tested with Mako G192C camera.

### CODE REVIEW

**Comment by icolwell-as** [comment]
Thanks @jmoreau-hds, I noticed the [G192](https://www.alliedvision.com/en/products/cameras/detail/Mako%20G/G-192/action/pdf.html) supports the following pixelformats:

> Monochrome pixel formats: Mono8, Mono10
YUV color pixel formats: YUV411Packed, YUV422Packed, YUV444Packed
RGB color pixel formats: RGB8Packed, BGR8Packed
Raw pixel formats: BayerGB8, BayerGB10

Why does your commit add much more pixel formats than what your camera supports? (for example `Mono10Packed`)

**Comment by ghost** [comment]
I wanted to be more exhaustive.
There are a lot of PixelFormats in GenICam: https://www.emva.org/wp-content/uploads/GenICamPixelFormatValues.pdf

**Comment by icolwell-as** [comment]
The only thing I worry about is that the AVT cameras might not support all those formats, and adding them all might give users the wrong impression that the formats are supported.
That being said, AVT has a wide variety of cameras that each offer different formats, and I don't want to comb through all that documentation, so I agree that just adding all possible formats is the easiest approach for now. 

I'll open a new PR since this once seems to be including some unrelated commits, we also need to update the dynamic reconfigure options too.
Thanks!

**Comment by icolwell-as** [comment]
Closed in favour of #3

**Pull request closed without merging**
